let pen=document.getElementById("wish");
console.log(Pen);
let mouse =document.getElementsByClassName("wishes");
console.log(mouse);
let cable=document.getElementsByClassName("wishes");
console.log(cable);
let water=document.getElementsByClassName("wishes");
console.log(water);
let queries=document.getElementsByClassName("wish");
console.log(queries);